### ISSUE TITLE
What is the signing key for the release?

### ISSUE THREAD

**Issue by fossfreedom** [BuddiesOfBudgie/budgie-backgrounds#41]
I took the signing key for budgie-desktop and budgie-desktop-view but both failed to validate the v1.0 package.

So can I ask - who has signed the package and what is the public key that is associated?

```
gpg --verify budgie-backgrounds_1.0.orig.tar.xz.asc budgie-backgrounds_1.0.orig.tar.xz
gpg: Signature made Fri 06 Jan 2023 22:53:41 GMT
gpg:                using RSA key 8A59B135826B2DA453B9707408AD7343E6BD4B56
gpg: Can't check signature: No public key
```

**Comment by serebit** [comment]
https://keyserver.ubuntu.com/pks/lookup?search=8A59B135826B2DA453B9707408AD7343E6BD4B56&fingerprint=on&op=index
